# This is a basic workflow to help you get started with Actions

name: Unit Test

# Controls when the action will run. 
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      PUID: 1001
      PGID: 1001
      MANGA_PATH: "./tests/data/container/manga/"
      SOURCE_PATH: "./tests/data/container/[source]/"
      DESTINATION_PATH: "./tests/data/container/[destination]/"
      ERROR_PATH: "./tests/data/container/error_msg/"
      DB_FILE_PATH: "./tests/data/container/db/test_manga.db"

      TEMPLATE_PATH: "./tests/data/container/[epub_template]/"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.4
      - run: python3 -m unittest discover
          

      # Runs a single command using the runners shell

      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
